#!/bin/bash

##
# addword -- add words to aspell personal dictionary
#
# usage -- addword WORD [WORD...]
#
# written -- 19 December, 2011 by Egan McComb
#
# revised --
##

ERR_NARGS=3

PWSFILE="$HOME/.aspell.en.pws"

usage()
{
	echo "Usage: $(basename $0) WORD [WORD...]" >&2
}

chkargs()
{
	if [ -z $1 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	fi
}

chkargs $@
WORDS=($@)

for WORD in ${WORDS[@]}
do
	echo $WORD >> $PWSFILE
done

NUM=$(($(wc -l $PWSFILE | cut -d " " -f 1)-1))
echo $NUM
< $PWSFILE sed -e "1s/ [0-9]* / $NUM /" | sponge $PWSFILE

exit 0
