#!/bin/bash

##
# addword -- add words to aspell personal dictionary
#
# usage -- addword WORD [WORD...]
#
# written -- 19 December, 2011 by Egan McComb
#
# revised --
##

err_nargs=3

pwsfile="$HOME/.aspell.en.pws"

usage()
{
	echo "Usage: $(basename $0) WORD [WORD...]" >&2
}

chkargs()
{
	if [ -z $1 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	fi
}

chkargs $@
words=($@)

for word in ${words[@]}
do
	echo $word >> $pwsfile
done

num=$(($(wc -l $pwsfile | cut -d " " -f 1)-1))
echo $num
< $pwsfile sed -e "1s/ [0-9]* / $num /" | sponge $pwsfile

exit 0
