#!/bin/bash

##
# addword	-- add words to aspell personal dictionary
#
# usage		-- addword WORD [WORD...]
#
# written	-- 19 December, 2011 by Egan McComb
#
# revised --
##

pwsfile="$HOME/.aspell.en.pws"

usage()
{
	echo "Usage: $(basename $0) WORD [WORD...]" >&2
}

chkargs()
{
	if (( ! $# ))
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	fi
}

chkargs "$@"
words=("$@")

for word in "${words[@]}"
do
	echo "$word" >> $pwsfile
done

num=$(($(wc -l $pwsfile | cut -d " " -f 1)-1))
< $pwsfile sed -e "1s/ [0-9]* / $num /" | sponge $pwsfile

exit 0
