#!/bin/bash

##
# backup	-- sync home directory to external hard disk
#
# usage		-- backup
#
# notes		-- requires rsync
#		-- pertinent partition must be mounted
#		-- additional files specified in $lst
#		   will be copied to $etc before syncing
#		-- exclusions and inclusions thereto are
#		   specified in $exc and $inc, respectively
#
# written	-- 2008 by Egan McComb
#
# revised	-- 11 July, 2009 by author
#		-- 19 December, 2011 by author
#		-- 29 December, 2011 by author
##

dir="arch-backup"
dsk="/media/Pangolin"
etc="$HOME/code/config/etc"
exc="$HOME/.rsync/exclude"
inc="$HOME/.rsync/include"
lst="$HOME/bin/.backup"

rsync()
{
	command rsync -av --delete --exclude-from="$exc" --include-from="$inc" "$1" "$2"
}

##----MAIN----##
while read file
do
	cp -R "$file" "$etc"
done < "$lst"
echo "Copied files listed in '$(basename "$lst")'"
echo "Attempting sync..."

if mountpoint -q "$dsk" || [[ -d "$dsk/$dir" ]]
then
	rsync $HOME "$dsk/$dir" || { echo "Error: rsync encountered an error"; exit 1; }
else
	echo "Error: Invalid destination '$dsk/$dir'"
	echo "       Ensure the medium is mounted properly"
	exit 2
fi

exit 0
