#!/bin/bash

##
# backup -- rsync home directory to external hard disk
#
# usage -- backup
#
# notes -- pertinent partition must be mounted
#
# written -- 2008 by Egan McComb
#
# revised -- 11 July, 2009 by author
##

dsk="Pangolin"
dir="arch-backup"
etc="$HOME/code/config/etc"

cp -R $(< $HOME/bin/.backup tr '\n' ' ')  $etc

# Check that $dsk is mounted
if mountpoint -q /media/$dsk
then
	# sync recursively, deleting old files
	rsync -av --delete --exclude-from="/home/egan/.rsync/exclude" --include-from="/home/egan/.rsync/include" $HOME /media/$dsk/$dir
else
	echo "Error: '$dsk' is not mounted"
	exit 1
fi

exit 0
