#!/bin/bash

##
# beep -- beep continuously or n times
#
# usage -- beep [-t NUMBER]
#
# written -- 27 July, 2010 by Egan McComb
#
# revised --
##

ERR_NARGS=3
ERR_VARGS=5

SNDFILE="$HOME/bin/.beep.wav"
COMMAND="aplay"
COPTION="$SNDFILE &>/dev/null"
SDEVICE="Master"

usage()
{
	echo "Usage: $(basename $0) [-t NUMBER]" >&2
}

chkargs()
{
	if [ -z "$1" ]
	then
		BCFUNCT="loop"
	elif [ $1 = "-t" ]
	then
		if [ -z "$2" ]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $ERR_NARGS
		elif $(echo $2 | grep -q [^[:digit:]])
		then
			echo "Error: Invalid NUMBER '$2'" >&2
			usage
			exit $ERR_VARGS
		elif [ $# -gt 2 ]
		then
			echo "Error: Too many arguments" >&2
			usage
			exit $ERR_NARGS
		else
			BCFUNCT="loop $2"
		fi
	else
		echo "Error: Invalid argument '$1'" >&2
		usage
		exit $ERR_VARGS
	fi
}

loop()
{
	if [ -z "$1" ]
	then
		while true
		do
			eval $COMMAND $COPTION
		done &
		trap "kill $! && echo 'Caught SIGINT: Break'; exit 1" SIGINT SIGKILL
		read -sn 1
		kill $!
	else
		i=$1
		while [ $i -gt 0 ]
		do
			eval $COMMAND $COPTION
			let i-=1
		done
	fi
}

unmute()
{
	if $(amixer | grep -A 4 \'$SDEVICE\' | awk {'print $6'} | grep -q  "\[off\]")
	then
		amixer -q set $SDEVICE toggle
	fi
}

##----MAIN----##
if [ ! -e $SNDFILE ]
then
	echo "Error: Missing resource '$SNDFILE'" >&2
	exit 1
fi

chkargs $*
unmute
$BCFUNCT

exit 0
