#!/bin/bash

##
# beep -- beep continuously or n times
#
# usage -- beep [-t NUMBER]
#
# written -- 27 July, 2010 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

sndfile="$HOME/bin/.beep.wav"
command="aplay"
coption="$SNDFILE &>/dev/null"
sdevice="Master"

usage()
{
	echo "Usage: $(basename $0) [-t NUMBER]" >&2
}

chkargs()
{
	if [ -z "$1" ]
	then
		bcfunct="loop"
	elif [ $1 = "-t" ]
	then
		if [ -z "$2" ]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $err_nargs
		elif $(echo $2 | grep -q [^[:digit:]])
		then
			echo "Error: Invalid NUMBER '$2'" >&2
			usage
			exit $err_vargs
		elif [ $# -gt 2 ]
		then
			echo "Error: Too many arguments" >&2
			usage
			exit $err_nargs
		else
			bcfunct="loop $2"
		fi
	else
		echo "Error: Invalid argument '$1'" >&2
		usage
		exit $err_vargs
	fi
}

loop()
{
	if [ -z "$1" ]
	then
		while true
		do
			eval $command $coption
		done &
		trap "kill $! && echo 'Caught SIGINT: Break'; exit 1" SIGINT SIGKILL
		read -sn 1
		kill $!
	else
		i=$1
		while [ $i -gt 0 ]
		do
			eval $command $coption
			let i-=1
		done
	fi
}

unmute()
{
	if $(amixer | grep -A 4 \'$sdevice\' | awk {'print $6'} | grep -q  "\[off\]")
	then
		amixer -q set $sdevice toggle
	fi
}

##----MAIN----##
if [ ! -e $sndfile ]
then
	echo "Error: Missing resource '$sndfile'" >&2
	exit 1
fi

chkargs $*
unmute
$bcfunct

exit 0
