#!/bin/bash

##
# beep		-- beep continuously or n times
#
# usage		-- beep [-t NUMBER]
#
# written	-- 27 July, 2010 by Egan McComb
#
# revised --
##

sndfile="$HOME/bin/.beep.wav"
sdevice="Master"

usage()
{
	echo "Usage: $(basename $0) [-t NUMBER]" >&2
}

play()
{
	aplay $sndfile &> /dev/null
}

chkargs()
{
	if (( ! $# ))
	then
		bcfunct="loop"
	elif [[ $1 = "-t" ]]
	then
		if [[ -z $2 ]]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $ERR_NARGS
		elif grep -q [^[:digit:]] <<< "$2"
		then
			echo "Error: Invalid NUMBER '$2'" >&2
			usage
			exit $ERR_VARGS
		elif [[ $# > 2 ]]
		then
			echo "Error: Too many arguments" >&2
			usage
			exit $ERR_NARGS
		else
			bcfunct="loop $2"
		fi
	else
		echo "Error: Invalid argument '$1'" >&2
		usage
		exit $ERR_VARGS
	fi
}

loop()
{
	if (( ! $# ))
	then
		while true
		do
			play
		done &
		trap "kill $! && echo 'Caught SIGINT: Break'; exit 1" SIGINT SIGKILL
		read -sn 1
		kill $!
	else
		i=$1
		while [[ $i > 0 ]]
		do
			play
			((i--))
		done
	fi
}

unmute()
{
	if amixer | grep -A 4 \'$sdevice\' | awk {'print $6'} | grep -q  "\[off\]"
	then
		amixer -q set $sdevice toggle
	fi
}

##----MAIN----##
if [[ ! -e $sndfile ]]
then
	echo "Error: Missing resource '$sndfile'" >&2
	echo "       Will generate tone instead" >&2
	speaker-test -t sine
	exit 0
fi

chkargs "$@"
unmute
$bcfunct

exit 0
