#!/bin/bash

##
# blog -- obtain fresh blender commit logs and view them.
#
# usage -- blog
#
# notes -- more repositories can be added as cases for $1
#	   will ultimately be replaced with svnnew
#
# written -- 1 March, 2009 by Egan McComb
#
# revised -- 11 July, 2009 by author
##

err_nargs=3
err_vargs=5

btk=$HOME/src/blender/blender

nfile=".svn/revision.info"

if [ $# -lt 2 ]
then
	case "$1" in
		'')		cd $btk;;
		*)		echo "Error: Not a valid repository '$1'" >&2
				exit $err_vargs;;
	esac
else
	echo "Error: Too many arguments" >&2
	exit $err_nargs
fi

if [ ! -s $nfile ]
then
	echo "Error: Data file does not exist or is empty: Creating" >&2
	echo -n "Enter a revison number to begin: " >&2
	read response
	echo $response > $nfile
	echo "Created $pwd/revision.info" >&2
fi

read=$(($(cat $nfile)+1))
svn log --incremental -r $read:BASE | less
svn info | grep 'Revision' | cut -d " " -f 2 > $nfile

exit 0
