#!/bin/bash

##
# bsup -- sync blender source tree to svn server
#
# usage -- bsup
#
# notes -- will ultimately be replaced with svnup
#
# written -- 2008 by Egan McComb
#
# revised -- 11 July, 2009 by Egan McComb
##

cd $HOME/src/blender/blender
svn up
date +%T\ on\ %D

exit 0
