#!/bin/bash

##
# catpdf	-- concatenate pdfs together
#
# usage		-- catpdf INFILES OUTFILE
#
# notes		-- requires ghostscript and userbool.sh
#
# written	-- 6 June, 2011 by Egan McComb
#
# revised	-- 19 December, 2011 by author
##

usage()
{
	echo "Usage: $(basename $0) INFILES OUTFILE" >&2
}

gs()
{
	command gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite "$@"
}

chkargs()
{
	if (( $# < 3 ))
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	elif [[ -f "${!#}" ]]
	then
		echo "Warning: Output file exists" >&2
		echo -n "Continue? [y/N] " >&2
		read response
		if ! userbool.sh $response
		then
			echo "Aborting..." >&2
			exit 1
		else
			echo "Continuing..." >&2
		fi
	fi
	for file in "${@:1:$(($#-1))}"
	do
		if [[ ! -e "$file" ]]
		then
			echo "Error: Invalid file '$file'" >&2
			exit $ERR_VARGS
		fi
	done
}

##----MAIN----##
chkargs "$@"
gs  -sOutputFile="${!#}" "${@:1:$(($#-1))}" || { echo "Errors occurred!" >&2; exit 1; }
exit 0
