#!/bin/bash

##
# catpdf -- cat pdfs together with ghostscript
#
# usage -- catpdf INFILES OUTFILE
#
# written -- 6 June, 2011 by Egan McComb
#
# revised --
##

ERR_NARGS=3
ERR_VARGS=5

COMMAND="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"

usage()
{
	echo "Usage: $(basename $0) INFILES OUTFILE" >&2
}

chkargs()
{
	if [ $# -lt 3 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	fi
	if [ -f ${!#} ]
	then
		echo "Warning: Output file exists" >&2
		echo -n "Continue? [y/N] " >&2
		read RESPONSE
		if [ "$RESPONSE" != "y" ]
		then
			exit 1
		fi
	fi
	OUT="${!#}"
	for FILE in "${@:1:$(($#-1))}"
	do
		if [ ! -e "$FILE" ]
		then
			echo "Error: Invalid file '$FILE'" >&2
			exit $ERR_VARGS
		fi
	done
}

##----MAIN----##
chkargs "$@"
$COMMAND  -sOutputFile="$OUT" "${@:1:$(($#-1))}"
exit 0
