#!/bin/bash

##
# catpdf -- cat pdfs together with ghostscript
#
# usage -- catpdf INFILES OUTFILE
#
# written -- 6 June, 2011 by Egan McComb
#
# revised -- 19 December, 2011 by author
##

err_nargs=3
err_vargs=5

command="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"

usage()
{
	echo "Usage: $(basename $0) INFILES OUTFILE" >&2
}

chkargs()
{
	if [ $# -lt 3 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	fi
	if [ -f "${!#}" ]
	then
		echo "Warning: Output file exists" >&2
		echo -n "Continue? [y/N] " >&2
		read response
		if [ "$response" != "y" ]
		then
			exit 1
		fi
	fi
	out="${!#}"
	for file in "${@:1:$(($#-1))}"
	do
		if [ ! -e "$file" ]
		then
			echo "Error: Invalid file '$file'" >&2
			exit $err_vargs
		fi
	done
}

##----MAIN----##
chkargs "$@"
$command  -sOutputFile="$out" "${@:1:$(($#-1))}"
exit 0
