#!/bin/bash

##
# chlink -- change the target of a symbolic link
#
# usage -- chlink [TARGET] LINK
#
# written -- 10 April, 2011 by Egan McComb
#
# revised --
##

ERR_NARGS=3
ERR_VARGS=5

usage()
{
	echo "Usage: $(basename $0) [TARGET] LINK" >&2
}

chkargs()
{
	if [ -z "$1" ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	elif [ $# -gt 2 ]
	then
		echo "Error: Too many arguments" >&2
		usage
		exit $ERR_NARGS
	fi
	if [ -z "$2" ]
	then
		chkfile "$1" -L
		TARGET=$(readlink -f "$1" | vipe)
		SYMLNK="$1"
	else
		chkfile "$1" -e
		TARGET="$1"
		chkfile "$2" -L
		SYMLNK="$2"
	fi
}

chkfile()
{
	if [ ! $2 "$1" ]
	then
		echo "Error: Invalid file '$1'" >&2
		usage
		exit $ERR_VARGS
	fi
}

##----MAIN----##
chkargs "$@"
rm "$SYMLNK" && ln -s "$TARGET" "$SYMLINK"

if [ $? -ne 0 ]
then
	echo "Error: Nonzero exit status" >&2
	exit 1
fi

exit 0
