#!/bin/bash

##
# colors	-- preview terminal colors
#
# usage		-- colors.sh
#
# written	-- 20 January, 2006 by Wolfgang Frisch
#
# revised	-- 2008 by Aaron Griffin
#		-- 29 December by Egan McComb
##


fgnames=(" black" "   red" " green" "yellow" "  blue" "magnta" "  cyan" " white")
bgnames=("BLK" "RED" "GRN" "YEL" "BLU" "MAG" "CYN" "WHT")

##----MAIN----##
for ((b=0; b<=7; b++))
do
	bg=$(($b+40))

	echo -en "\033[0m ${bgnames[$b]} :: "
	for ((f=0; f<=7; f++))
	do
		echo -en "\033[${bg}m\033[$(($f+30))m ${fgnames[$f]} "
	done

	echo -en "\033[0m\n\033[0m     :: "
	for ((f=0; f<=7; f++))
	do
		echo -en "\033[${bg}m\033[1;$(($f+30))m ${fgnames[$f]} "
	done
	echo -e "\033[0m"

	if (( $b < 7 ))
	then
		echo "     -------------------------------------------------------------------"
	fi
done

exit 0
