#!/bin/bash

##
# esplit -- split a file into pieces
#
# usage -- esplit -m | -c COUNT [FILE ...]
#
# written -- 27 May, 2009 by Egan McComb
#
# revised -- 12 July, 2009 by author
##

err_nargs=3
err_vargs=5

size=16777216

usage()
{
	echo "Usage: $(basename $0) -m | -c COUNT FILE..." >&2
}

chkargs()
{
	if [ $# -lt 2 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	elif [ ! $1 = "-m" ] && [ ! $1 = "-c" ]
	then
		echo "Error: Invalid argument '$1'" >&2
		usage
		exit $err_vargs
	fi
}

chkfile()
{
	if [ ! -e "$1" ]
	then
		echo "Error: Nonexistant file '$1'" >&2
		echo "Skipping..." >&2
		continue
	elif [ ! -f "$1" ]
	then
		echo "Error: Bad file '$1'" >&2
		echo "Skipping..." >&2
		continue
	fi
}

methodc()
{
	if [ "$1" = "-m" ]
	then
		method=magic
		nshift=shift
	else
		method=nsplit
		if [ -z "$2" ]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $err_nargs
		elif $(grep -q [^[:digit:]] <<< $2)
		then
			echo "Error: Invalid argument '$2'" >&2
			usage
			exit $err_vargs
		else
			method="nsplit $2"
			nshift="shift && shift"
		fi
	fi
}


magic()
{
	split -b $size "$1" "$1".
	echo "Split file $file into pieces of $size bytes"
}

nsplit()
{
	fsize=$(command ls -l "$2" | cut -d " " -f 5)
	ssize=$(($fsize/$1))
	split -b $ssize "$2" "$2".
	echo "Split file $2 into $1 pieces of $ssize bytes"
}

###----MAIN----###
chkargs "$@"
methodc "$@"
$nshift
for file in "$@"
do
	chkfile "$file"
	$METHOD "$file"
done

exit 0
