#!/bin/bash

##
# excpdf -- remove pages from pdfs with ghostscript
#
# usage -- excpdf PAGERANGE INFILE OUTFILE
#
# written -- 19 December, 2011 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

trimcom="tr ':\-,' '\n'"
command="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite"

usage()
{
	echo "Usage: $(basename $0) PAGERANGE INFILE OUTFILE" >&2
	echo -e "\t-PAGERANGE is given with ranges" >&2
	echo -e "\t e.g. 3-5:7:9-15 keeps those pages" >&2
	echo -e "\t-Pages must be in numerical order" >&2
}

chkargs()
{
	if [ $# -ne 3 ]
	then
		echo "Error: Wrong number of arguments" >&2
		usage
		exit $err_nargs
	fi
	chkfile "$2" && in="$2"
	out="$3"
	if $(grep -q "[^[:digit:]:-]" <<< "$1")
	then
		echo "Error: Invalid page range syntax" >&2
		usage
		exit $err_vargs
	elif ! $(sort -nC <(eval $trimcom <<< $1)) || [ ! -z $(uniq -d <(eval $trimcom <<< $1)) ]
	then
		echo "Error: Invalid page range collation" >&2
		usage
		exit $err_vargs
	fi
}

chkfile()
{
	if [ ! -f "$1" ] || ! $(grep -q "PDF" <<< $(file "$1"))
	then
		echo "Error: Invalid input file '$1'" >&2
		exit $err_vargs
	fi
}

range()
{
	IFS=":"
	ranges=($@)
	tfiles=()
	for range in ${ranges[@]}
	do
		if [ $(awk 'BEGIN { FS="-"} ; { print NF }' <<< $range) -gt 2 ]
		then
			echo "Error: Invalid subrange '$range'" >&2
			usage
			exit $err_vargs
		fi
		IFS="-"
		subrange=(${range[@]})
		tfiles[${#tfiles[@]}]=$(mktemp)
		IFS=" "
		eval $command -dFirstPage=${subrange[0]} -dLastPage=${subrange[-1]} -sOutputFile="${tfiles[-1]}" "$in"
	done
	catpdf ${tfiles[@]} "$out"
	rm ${tfiles[@]}
}

chkargs "$@"
range $1

exit 0
