#!/bin/bash

astyle --indent=tab=4       \
	   --style=kr           \
	   --add-braces         \
	   --indent-switches    \
	   --convert-tabs       \
	   --pad-header         \
	   --unpad-paren        \
	   --pad-comma          \
	   --pad-oper           \
	   --align-pointer=name

