#!/bin/bash

##
# gweather -- obtain weather data using google api
#
# usage -- gweather [-c|--current]|[-f|--forecast][LOCID]
#
# note -- no protection against invalid LOCID
#
# written -- 12 September, 2010 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

current="$HOME/bin/.current.xslt"
forecast="$HOME/bin/.forecast.xslt"
locid="Mountain+View"
#locid="95616"

usage()
{
	echo "Usage: $(basename $0) [-c|--current]|[-f|--forecast] [LOCID]" >&2
	echo -e "\t-When unspecified, LOCID=$locid" >&2
	echo -e "\t-LOCID can be given as a string or zip code" >&2
}

chkargs()
{
	if [ $# == 0 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	elif [ $1 = "-f" ] || [ $1 = "--forecast" ]
	then
		FILTER=$forecast
	elif [ $1 = "-c" ] || [ $1 = "--current" ]
	then
		FILTER=$current
	elif [ $# -gt 1 ]
	then
		echo "Error: Too many arguments" >&2
		usage
		exit $err_nargs
	else
		echo "Error: Invalid arguments" >&2
		usage
		exit $err_vargs
	fi
	if [ ! -z "$2" ]
	then
		locid="$2"
	fi
}

##----MAIN---##
chkargs "$@"
curl -s http://www.google.com/ig/api?weather="$locid" | iconv -f ISO-8859-1 -t UTF-8 | xsltproc $filter -

exit 0
