#!/bin/bash

##
# imgur -- upload image to imgur.com
#
# usage -- imgur FILE
#
# notes -- stores history in ~/bin/.imgur_history
#
# todo -- thumbnail link?
#
# written -- 25 August, 2010 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

apikey="4f22353fbb8473a442bf708ecd553ffb"

hfile="$HOME/bin/.imgur_history"

usage()
{
	echo "Usage: $(basename $0) FILE" >&2
}

chkargs()
{
	if [ $# -ne 1 ]
	then
		if [ $# == 0 ]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $err_nargs
		else
			echo "Error: Too many arguments" >&2
			usage
			exit $err_nargs
		fi
	elif [ ! -f "$1" ]
	then
		echo "Error: Invalid file '$1'" >&2
		usage
		exit $err_vargs
	else
		image="$1"
	fi
}

##----MAIN----##
chkargs "$@"

response=$(curl -sF "key=$apikey" -F "image=@$image" http://imgur.com/api/upload.xml)

if [ $? -ne 0 ]
then
	echo "Upload failed" >&2
	exit 1
elif [ $(grep -c "<error_msg>" <<< $response) -gt 0 ]
then
	echo "Error: imgur says:" >&2
	echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
	exit 1
fi

iurl=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $response)
durl=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $response)

echo -n "$iurl" | xclip
date +%T\ on\ %D >> $hfile
echo "$iurl" | tee -a $hfile
echo "$durl" >> $hfile

exit 0
