#!/bin/bash

##
# imgur		-- upload image to imgur.com
#
# usage		-- imgur FILE
#
# notes		-- requires netbool.sh and tclip
#		-- stores history in $hfile
#
# todo		-- thumbnail link?
#
# written	-- 25 August, 2010 by Egan McComb
#
# revised --
##

apikey="4f22353fbb8473a442bf708ecd553ffb"

hfile="$HOME/bin/.imgur_history"

usage()
{
	echo "Usage: $(basename $0) FILE" >&2
}

chkargs()
{
	if (( $# != 1 ))
	then
		if (( ! $# ))
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $ERR_NARGS
		else
			echo "Error: Too many arguments" >&2
			usage
			exit $ERR_NARGS
		fi
	elif [[ ! -f "$1" ]]
	then
		echo "Error: Invalid file '$1'" >&2
		usage
		exit $ERR_VARGS
	else
		image="$1"
	fi
}

##----MAIN----##
if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

chkargs "$@"

response=$(curl -sF "key=$apikey" -F "image=@$image" http://imgur.com/api/upload.xml)

if (( $? != 0 ))
then
	echo "Error: Upload failed" >&2
	exit 1
elif (( $(grep -c "<error_msg>" <<< $response) > 0 ))
then
	echo "Error: imgur says:" >&2
	echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
	exit 2
fi

iurl=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $response)
durl=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $response)

date +%T\ on\ %D >> $hfile
echo "$iurl" | tee -a $hfile | tclip
echo "$durl" >> $hfile

exit 0
