#!/bin/bash

##
# imgur -- upload image to imgur.com
#
# usage -- imgur FILE
#
# notes -- stores history in ~/bin/.imgur_history
#
# todo -- thumbnail link?
#
# written -- 25 August, 2010 by Egan McComb
#
# revised --
##

ERR_NARGS=3
ERR_VARGS=5

APIKEY="4f22353fbb8473a442bf708ecd553ffb"

HFILE="$HOME/bin/.imgur_history"

usage()
{
	echo "Usage: $(basename $0) FILE" >&2
}

chkargs()
{
	if [ $# -ne 1 ]
	then
		if [ $# == 0 ]
		then
			echo "Error: Too few arguments" >&2
			usage
			exit $ERR_NARGS
		else
			echo "Error: Too many arguments" >&2
			usage
			exit $ERR_NARGS
		fi
	elif [ ! -f "$1" ]
	then
		echo "Error: Invalid file '$1'" >&2
		usage
		exit $ERR_VARGS
	else
		IMAGE="$1"
	fi
}

##----MAIN----##
chkargs "$@"

RESPONSE=$(curl -sF "key=$APIKEY" -F "image=@$IMAGE" http://imgur.com/api/upload.xml)

if [ $? -ne 0 ]
then
	echo "Upload failed" >&2
	exit 1
elif [ $(grep -c "<error_msg>" <<< $RESPONSE) -gt 0 ]
then
	echo "Error: imgur says:" >&2
	echo $RESPONSE | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
	exit 1
fi

IURL=$(sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/' <<< $RESPONSE)
DURL=$(sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/' <<< $RESPONSE)

echo -n "$IURL" | xclip
date +%T\ on\ %D >> $HFILE
echo "$IURL" | tee -a $HFILE
echo "$DURL" >> $HFILE

exit 0
