#!/bin/bash

##
# lint    -- invoke PC-lint
#
# notes   -- this script assumes Lint is in your $PATH
#
# usage   -- lint CONFIG ARGS
#
# written -- 1 January, 2018 by Egan McComb
#
# revised --
##

CONFIGDIR='/c/Users/eganmccomb/.lint/'

Lint-nt +v -i$CONFIGDIR $@ | less

