#!/bin/bash

##
# lnmv		-- replace a file with a symbolic link to its new location
#
# usage		-- lnmv OLDFILE NEWFILE
#
# notes		-- the new filename must be given
#		   even if it is not to be renamed
#
# written	-- 7 April, 2011 by Egan McComb
#
# revised	--
##

usage()
{
	echo "Usage: $(basename $0) OLDFILE NEWFILE" >&2
	echo -e "\t-Note: The new filename must be given" >&2
	echo -e "\t       even if it is not to be renamed." >&2
}

chkargs()
{
	if (( $# != 2 ))
	then
		echo "Error: Wrong number of arguments" >&2
		usage
		exit $ERR_NARGS
	elif [[ ! -f "$2" ]]
	then
		echo "Error: Invalid filename '$2'">&2
		usage
		exit $ERR_VARGS
	fi
}

##----MAIN----##
chkargs "$@"

oldfile="$1"
newfile=$(readlink -f "$2")

mv "$1" "$2" && ln -s "$newfile" "$oldfile" || { echo "Errors occurred!" >&2; exit 1; }

exit 0
