#!/bin/bash

##
# lnmv -- replace a file with a symbolic link to its new location
#
# usage -- lnmv OLDFILE NEWFILE
#
# written -- 7 April, 2011 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

usage()
{
	echo "Usage: $(basename $0) OLDFILE NEWFILE" >&2
	echo -e "\t-Note: The new filename must be given" >&2
	echo -e "\t       even if it is not to be renamed." >&2
}

chkargs()
{
	if [ $# -ne 2 ]
	then
		echo "Error: Wrong number of arguments" >&2
		usage
		exit $err_nargs
	fi
	if [ -d "$2" ]
	then
		echo "Error: Invalid filename '$2'">&2
		usage
		exit $err_vargs
	fi
}

##----MAIN----##
chkargs "$@"

oldfile="$1"
newfile=$(readlink -f "$2")

mv "$1" "$2" && ln -s "$newfile" "$oldfile"

if [ $? -ne 0 ]
then
	echo "Error: Unable to make link." >&2
	exit 1
fi

exit 0
