#!/bin/bash

##
# mkoff -- prepare a website for offline use
#
# usage -- mkoff -s STRING [FILE]
#
# notes -- obviously the resources should be downloaded
#
# written -- 4 July, 2009 by Egan McComb
##

err_nargs=3
err_nargs=5

usage()
{
	echo "Usage: $(basename $0) -s STRING [FILE]" >&2
}

chkfile()
{
	if [ -z "$1" ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	elif [ ! -e "$1" ]
	then
		echo "Error: Nonexistent file: $1" >&2
		usage
		exit $err_vargs
	elif [ ! -f "$1" ]
	then
		echo "Error: Wrong type of file: $1" >&2
		usage
		exit $err_vargs
	else
		FILE="$1"
	fi
}

##----MAIN----##

if [ $1 = "-s" ]
then
	if [ ! -z "$2" ]
	then
		string="$2"
		chkfile "$3"
		cp "$file" "$file"~
		sed "s|${string}||g" "$file" | sponge "$file"
	else
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	fi
else
	chkfile "$1"
	cp "$file" "$file"~
	perl -p0e 's|<a href="(.*://.*?/)(.*")|<a href="./$2|g' "$file" | sponge "$file"
fi

exit 0
