#!/bin/bash

##
# mkoff		-- prepare a website for offline use
#
# usage		-- mkoff [-s STRING] FILE
#
# notes		-- obviously the resources should be downloaded
#
# written	-- 4 July, 2009 by Egan McComb
#
# revised	-- 29 December, 2011 by author
##

usage()
{
	echo "Usage: $(basename $0) -s STRING [FILE]" >&2
}

chkfile()
{
	if [[ ! -f "$1" ]]
	then
		echo "Error: Invalid file '$1'" >&2
		usage
		exit $ERR_VARGS
	fi
}

strsub()
{
	cp "$1" "$1"~
	sed "s|${string}||g" "$1" | sponge "$1"
}

relsub()
{
	cp "$1" "$1"~
	perl -p0e 's|<a href="(.*://.*?/)(.*")|<a href="./$2|g' "$1" | sponge "$1"
}

chkargs()
{
	if (( ! $# ))
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	elif [[ $1 = "-s" ]]
	then
		if [[ ! -z "$2" ]]
		then
			string="$2"
			chkfile "$3"
			strsub "$3"
		else
			echo "Error: Too few arguments" >&2
			usage
			exit $ERR_NARGS
		fi
	else
		chkfile "$1"
		relsub "$1"
	fi
}

##----MAIN----##
chkargs "$@"

exit 0
