#!/bin/bash

##
# mkwcfg -- creates wireless network profile
#
# usage -- wconn ESSID [TYPE] [KEY]
#
# todo -- autodetect network type and prompt for key
#
# written -- 1 January, 2011 by Greg Dwulet
#
# revised -- 13 March, 2011 by Egan McComb
##

ERR_NARGS=3
ERR_VARGS=5

NETDIR="/etc/network.d"

usage()
{
	echo "Usage: $(basename $0) ESSID [wep|wpa] [KEY]" >&2
}

chkargs()
{
	if [ -z "$1" ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	elif [ $# -gt 3 ]
	then
		echo "Error: Too many arguments" >&2
		usage
		exit $ERR_NARGS
	fi
}

doargs()
{
	if [ $# -eq 1 ]
	then
		if $(sudo iwlist wlan0 scan | piwlist.py | grep -q "$1")
		then
			ESSID="$1"
			FILE="$NETDIR/$ESSID-wireless"
		else
			echo "Error: Unknown wireless network '$1'" >&2
			usage
			exit $ERR_VARGS
		fi
	elif [ $# -eq 2 ]
	then
		echo "Error: Incorrect arguments" >&2
		usage
		exit $ERR_VARGS
	else
		if [ $2 != "wep" ] && [ $2 != "wpa" ]
		then
			echo "Error: Invalid network type '$2'" >&2
			usage
			exit $ERR_VARGS
		else
			TYPE=$2
			KEY="$3"
		fi
		if $(sudo iwlist wlan0 scan | piwlist.py | grep -q "$1")
		then
			ESSID="$1"
			FILE="$NETDIR/$ESSID-wireless"
		else
			echo "Error: Unknown wireless network '$1'" >&2
			usage
			exit $ERR_NARGS
		fi
	fi
}

makeprofile()
{
	if [ ! -e "$FILE" ]
	then
		cp $NETDIR/examples/wireless-$TYPE "$FILE"
		editprofile "$ESSID" $TYPE "$KEY"
	fi
}

editprofile()
{
	sed -i "s/MyNetwork/$ESSID/" "$FILE"
	if [ $TYPE = "wep" ]
	then
		sed -i "s/123456789/$KEY/" "$FILE"
	elif [ $TYPE = "wpa" ]
	then
		sed -i "s/WirelessKey/$KEY/" "$FILE"
	fi
	echo "DHCP_TIMEOUT='3000'" >> "$FILE"
}

##----MAIN----##
if [ $EUID != "0" ]
then
	echo "Error: Must be root"
	exit 1
fi

chkargs "$@"
doargs "$@"
makeprofile

exit 0
