#!/bin/bash

##
# radar   -- obtain radar reflectivity data from NWS
#
# usage   -- radar
#
# notes   -- requires qiv
#         -- DAX - Sacramento station
#
# todo    -- add locid argument
#         -- potentially automatic determination of station?
#
# written -- 11 December, 2010 by Egan McComb
#
# revised -- 13 July, 2012 by Aaron Huffman
##

curl()
{
	command curl -so "$@"
}

merge()
{
	convert -layers merge "$@"
}


locid="DAX"
m_dir="$HOME/bin/.radar/${locid}"
m_every="$m_dir/comp-stat.gif"
m_out="$m_dir/comp-all.gif"

m_topo="http://radar.weather.gov/Overlays/Topo/Short/${locid}_Topo_Short.jpg"
m_cnty="http://radar.weather.gov/Overlays/County/Short/${locid}_County_Short.gif"
m_rivr="http://radar.weather.gov/Overlays/Rivers/Short/${locid}_Rivers_Short.gif"
m_hywy="http://radar.weather.gov/Overlays/Highways/Short/${locid}_Highways_Short.gif"
m_city="http://radar.weather.gov/Overlays/Cities/Short/${locid}_City_Short.gif"
m_warn="http://radar.weather.gov/Warnings/Short/${locid}_Warnings_0.gif"
m_radr="http://radar.weather.gov/ridge/RadarImg/N0R/${locid}_N0R_0.gif"
m_over="http://radar.weather.gov/Legend/N0R/${locid}_N0R_Legend_0.gif"

m_topo_f=${m_dir}/statics/topo.jpg
m_cnty_f=${m_dir}/statics/county.gif
m_rivr_f=${m_dir}/statics/river.gif
m_hywy_f=${m_dir}/statics/highways.gif
m_city_f=${m_dir}/statics/cities.gif
m_warn_f=${m_dir}/warnings-t.gif
m_radr_f=${m_dir}/radar-t.gif
m_over_f=${m_dir}/legend-t.gif

##----MAIN----##
if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

if [ ! -d "$m_dir" ]
then
	mkdir "$m_dir" "$m_dir/statics"

	curl $m_topo_f $m_topo &
	pids=$!
	curl $m_cnty_f $m_cnty &
	pids="$pids $!"
	curl $m_rivr_f $m_rivr &
	pids="$pids $!"
	curl $m_hywy_f $m_hywy &
	pids="$pids $!"
	curl $m_city_f $m_city &
	pids="$pids $!"

	wait $pids
	merge $m_topo_f $m_hywy_f $m_rivr_f $m_cnty_f $m_city_f $m_every
fi

curl $m_warn_f $m_warn &
pids=$!
curl $m_radr_f $m_radr &
pids="$pids $!"
curl $m_over_f $m_over &
pids="$pids $!"

wait $pids
merge $m_every $m_warn_f $m_radr_f $m_over_f $m_out
qiv $m_out

exit 0
