#!/bin/bash

##
# radar		-- obtain radar reflectivity data from NWS
#
# usage		-- radar
#
# notes		-- requires qiv
#		-- uses DAX station
#
# todo		-- allow changeable LOCID
#
# written	-- 11 December, 2010 by Egan McComb
#
# revised	--
##

curl()
{
	command curl -so "$@"
}

merge()
{
	convert -layers merge "$@"
}


locid="dax"
m_dir="$HOME/bin/.radar"
m_out="$m_dir/${locid}_comp-t.gif"

m_topo="$m_dir/${locid}_topo.gif"
m_cnty="$m_dir/${locid}_county.gif"
m_rivr="$m_dir/${locid}_river.gif"
m_hywy="$m_dir/${locid}_hwy.gif"
m_city="$m_dir/${locid}_city.gif"

m_warn="$m_dir/${locid}_warn-t.gif"
m_radr="$m_dir/${locid}_radar-t.gif"
m_over="$m_dir/${locid}_legend-t.gif"

m_evry="$m_dir/${locid}_all.gif"

m_warn_u="http://radar.weather.gov/Warnings/Short/DAX_Warnings_0.gif"
m_radr_u="http://radar.weather.gov/ridge/RadarImg/N0R/DAX_N0R_0.gif"
m_over_u="http://radar.weather.gov/Legend/N0R/DAX_N0R_Legend_0.gif"

##----MAIN----##
if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

curl $m_warn $m_warn_u &
pids=$!
curl $m_radr $m_radr_u &
pids="$pids $!"
curl $m_over $m_over_u &
pids="$pids $!"

wait $pids
merge $m_evry $m_warn $m_radr $m_over $m_out
qiv $m_out

exit 0
