#!/bin/bash

##
# statmirrors -- output update status of pacman mirrors
#
# usage -- statmirrors
#
# written -- 26 July, 2010 by Egan McComb
#
# revised -- 9 April, 2011 by author
##

staturl="https://www.archlinux.de/?page=MirrorStatusReflector"
mirrorl="/etc/pacman.d/mirrorlist"
serverl=$(sed '/^ *Server *= *\([^\$]*\)\$repo.*$/!d;s//\1/' /etc/pacman.d/mirrorlist | tr '\n' '|' | sed 's/|$//')

##----MAIN----$$
grep -E "$serverl" <(curl -s $staturl)

exit 0
