#!/bin/bash

##
# svnnew -- obtain fresh svn commit logs and view them
#
# usage -- svnlog
#
# notes -- finds last revision in file $PWD/.svn/revision.info
#
# written -- 1 March 2009 by Egan McComb
#
# revised -- 22 August, 2010 by author
##

nfile=".svn/revision.info"
lfile=".svn/revision.log"

if [ ! -s $nfile ]
then
	echo "Error: No revision file found, exiting" >&2
	exit 1
fi

read=$(($(cat $nfile)+1))
svn log --incremental -r $read:BASE | tee -a $lfile | less
svn info | grep 'Revision' | cut -d " " -f 2 > $nfile

exit 0
