#!/bin/bash

##
# svnnew	-- obtain fresh svn commit logs and view them
#
# usage		-- svnlog
#
# notes		-- intended for use with aliases for specific repos
#
# written	-- 1 March 2009 by Egan McComb
#
# revised	-- 11 July, 2009 by author
#		-- 22 August, 2010 by author
##

nfile="./.svn/revision.info"

if [[ ! -d ./.svn ]]
then
	echo "Error: Invalid svn repo '$PWD'" >&2
	exit $ERR_VARGS
elif [[ ! -s "$nfile" ]]
then
	echo "Error: Revision information unavailable: Creating" >&2
	while true
	do
		echo -n "Enter an initial revision number: " >&2
		read response
		if grep -q [^[:digit:]] <<< $response
		then
			echo "Error: Invalid revision number '$response'" >&2
		else
			break
		fi
	done
	echo $response > "$nfile"
	echo "Created $pwd/$nfile" >&2
fi

if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

read=$(($(cat "$nfile")+1))
svn log --incremental -r $read:BASE | less
svn info | grep 'Revision' | cut -d " " -f 2 > "$nfile"

exit 0
