#!/bin/bash

##
# svnup -- sync svn source trees to svn server
#
# usage -- svnup [-h|--help]|[-o|--only][DIR...]
#
# notes -- default repos are newline-delimited in ~/bin/.svnlist
#
# written -- 2008 by Egan McComb
#
# revised -- 22 August, 2010 by author
##

ifs=":"
err_vargs=5

lfile="$HOME/bin/.svnlist"
sline="\E[01;34m::\033[0m Updating:"
tline="\E[01;34m>\033[0m"

usage()
{
	echo "Usage: $(basename $0) [-h|--help]|[-o|--only][DIR...]" >&2
	echo -e "\t-Directory arguments are concatenated" >&2
	echo -e "\t to newline-delimited default list $lfile" >&2
	echo -e "\t unless the '-o' option is passed" >&2
}

chkfile()
{
	if [ ! -d "$1" ]
	then
		echo "Error: Nonexistent directory '$1'" >&2
		exit $err_vargs
	else
		if [ ! -d "$1"/.svn ]
		then
			echo "Error: Invalid svn repo '$1'" >&2
			exit $err_vargs
		fi
	fi
}

chkargs()
{
	if [ $# -ne 0 ]
	then
		if [ $1 = "-h" ] || [ $1 = "--help" ]
		then
			usage
			exit 0
		elif [ $1 = "-o" ] || [ $1 = "--only" ]
		then
			shift
			for arg in "$@"
			do
				chkfile "$arg"
				repos="$repos $arg"
			done
		else
			repos="$(cat $lfile | tr '\n' ' ')"
			for arg in "$@"
			do
				chkfile "$arg"
				repos="$repos $arg"
			done
		fi
	else
		repos=$(cat $lfile | tr '\n' ':')
	fi
}

##----MAIN----##
chkargs "$@"

for dir in "$repos"
do
	echo -e "$sline ${dir/\/home\/egan/~}"
	cd "$dir" && svn up && cd
	echo -ne "$tline "
	date +%T\ on\ %D
	echo
done

exit 0
