#!/bin/bash

##
# swap		-- swap file names
#
# usage		-- swap FILE1 FILE2
#
# written	-- 12 Dec, 2009 by Egan McComb
#
# revised	-- 25 Dec, 2010 by author
##

usage()
{
	echo "Usage: $(basename $0) FILE1 FILE2" >&2
}

chkargs()
{
	if [[ $# != 2 ]]
	then
		echo "Error: Wrong number of arguments" >&2
		usage
		exit $ERR_NARGS
	fi
}

chkfile()
{
	for file in "$@"
	do
		if [[ ! -e "$file" ]]
		then
			echo "Error: Invalid file '$1'" >&2
			usage
			exit $ERR_VARGS
		fi
	done
}

##----MAIN----##
chkargs "$@"
chkfile "$@"

temp=$(mktemp swap.XXXXXXXXXX)
mv "$1" $temp && mv "$2" "$1" && mv $temp "$2" || { echo "Errors occured!"; exit 1; }
exit 0
