#!/bin/bash

##
# swap -- swap file names
#
# usage -- swap FILE1 FILE2
#
# written -- 12 Dec, 2009 by Egan McComb
#
# revised -- 25 Dec, 2010 by author
##

err_nargs=3
err_vargs=5

usage()
{
	echo "Usage: $(basename $0) FILE1 FILE2" >&2
}

chkargs()
{
	if [ $# -ne 2 ]
	then
		echo "Error: Wrong number of arguments" >&2
		usage
		exit $err_nargs
	fi
}

chkfile()
{
	for file in "$@"
	do
		if [ ! -e "$1" ]
		then
			echo "Error: File '$1' does not exist" >&2
			usage
			exit $err_vargs
		fi
	done
}

##----MAIN----##
chkargs "$@"
chkfile "$@"

temp=$(mktemp swap.XXX)
mv "$1" $temp && mv "$2" "$1" && mv $temp "$2" && exit 0
