#!/bin/bash

##
# tablize -- convert labeled tsv files to latex tables
#
# usage -- tablize [[-e ENVIRONMENT] [-c COLUMNSPEC] [-f FIELDSEP]] [FILE ...]
#
# written -- 30 April, 2010 by Egan McComb
#
# revised --
##

ERR_NARGS=3
ERR_VARGS=5

TE="tabular"
CS="l"
FS="	"

usage()
{
	echo "$(basename $0) [[-e ENVIRONMENT] [-c COLUMNSPEC] [-f FIELDSEP]] [FILE ...]" >&2
}

chkargs()
{
	if [ -z "$1" ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	fi
	if [ $# -gt 1 ]
	then
		while getopt "e:c:f:" OPT
		do
			case $OPT in
				e) TE=$OPTARG;;
				c) CS=$OPTARG;;
				f) FS=$OPTARG;;
				?) except $OPTARG;;
			esac
		done
	fi
}

chkfile()
{
	if [ ! -e "$1" ]
	then
		echo "Error: Invalid file: '$1'" >&2
		usage
		exit $ERR_VARGS
	fi
}

column()
{
	NF=$(awk 'END{printf "%s", NF}' < $IN)
	CSP=" |"$CS
	i="1"
	while [ $i -lt $NF ]
	do
		CSP=${CSP}$CS
		let i+=1
	done
}

convert()
{
	echo -e "\\\begin{$TE}{$CSP}\n\\toprule" > ${1/%.*/.tex}
	sed "s/$FS/ \& /g;s/$/ \\\\\\\\\n\\\\midrule/g" < $1 >> ${1/%.*/.tex}
	echo "\end{$TE}" >> ${1/%.*/.tex}
}

##---MAIN---##
chkargs "$@"
for FILE in "$@"
do
	chkfile "$FILE"
	column "$FILE"
	convert "$FILE"
done

exit 0
