#!/bin/bash

##
# tablize	-- convert labeled tsv files to latex tables
#
# usage		-- tablize [FILE ...]
#
# todo		-- add options for $te and $cs as well as headers
#
# written	-- 30 April, 2010 by Egan McComb
#
# revised	--
##

te="tabular"
cs="l"

usage()
{
	echo "$(basename $0) [FILE ...]" >&2
}

chkargs()
{
	if (( ! $# ))
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $ERR_NARGS
	fi
}

chkfile()
{
	if [[ ! -f "$1" ]]
	then
		echo "Error: Invalid file '$1'" >&2
		echo "Continuing..." >&2
		continue
	fi
}

column()
{
	nf=$(awk 'END{printf "%s", NF}' < "$1")
	csp=$cs
	for ((i=1; i<$nf; i++))
	do
		csp=$csp$cs
	done
}

convert()
{
	echo -e "\\\begin{$te}{$csp}\n\\topline" > "${1/%.*/.tex}"
	sed "s/	/ \& /g;s/$/ \\\\\\\\\n\\\\midline/g" < "$1" >> "${1/%.*/.tex}"
	sed "$s/midrule/bottomrule/g" < "${1/%.*/.tex}" | sponge "${1/%.*/.tex}"
	echo "\end{$te}" >> "${1/%.*/.tex}"
	echo "Converted '$1' to '${1/%.*/.tex}'" 
}

##---MAIN---##
chkargs "$@"
for file in "$@"
do
	chkfile "$file"
	column "$file"
	convert "$file"
done

exit 0
