#!/bin/bash

##
# tclip -- tee stdin to clipboard and stdout
#
# usage -- tclip
#
# written -- 7 July, 2010 by Egan McComb
#
# revised --
##

input=$(cat -)

echo -n "$input" | xclip
echo "$input"

exit 0
