#!/bin/bash

##
# tclip		-- tee stdin to clipboard and stdout
#
# usage		-- tclip
#
# notes		-- not safe for large data 
#
# todo		-- remove intermediate variable
#
# written	-- 7 July, 2010 by Egan McComb
#
# revised	--
##

if [[ -t 0 ]]
then
	echo "Error: No input given" >&2
	exit
fi

read -r input
echo -n $input | xclip
echo $input

exit 0
