#!/bin/bash

##
# tex2img -- quickly get png output from latex code (for math)
#
# usage -- tex2img [SIZE] STRING
#
# notes -- not many measures to prevent stupidity are in place
#
# written -- 25 August, 2010 by Egan McComb
#
# revised --
##

err_nargs=3
err_vargs=5

file=$(mktemp $(basename $0).XXX.tex)
size="\LARGE"
lcommand="latex -interaction=batchmode"
dcommand="dvipng -q -T tight -o ${file/%tex/png}"

usage()
{
	echo "Usage: $(basename $0) [SIZE] STRING" >&2
	echo -e "\t-SIZE is standard LaTeX size command name" >&2
	echo -e "\t without any substring 'size'" >&2
	echo -e "\t-Few measures preventing stupidity" >&2
	echo -e "\t are in place" >&2
	echo -e "\t-Single-quoting is recommended" >&2
}

chkargs()
{
	if [ $# -eq 0 ]
	then
		echo "Error: Too few arguments" >&2
		usage
		exit $err_nargs
	elif [ $# -eq 2 ]
	then
		case $1 in
			tiny)
				size="\tiny";;
			script)
				size="\scriptsize";;
			footnote)
				size="\footnotesize";;
			small)
				size="\small";;
			normal)
				size="\normal";;
			large)
				size="\large";;
			Large)
				size="\Large";;
			LARGE)
				size="\LARGE";;
			huge)
				size="\huge";;
			Huge)
				size="\Huge";;
			*)
				echo "Error: Invalid argument '$1'" >&2
				usage
				exit $err_vargs
		esac
		text="$2"
	elif [ $# -gt 2 ]
	then
		echo "Error: Too many arguments" >&2
		usage
		exit $err_nargs
	else
		text="$*"
	fi
}

convert()
{
	$lcommand $file > /dev/null
	if [ $? -ne 0 ]
	then
		echo "Error: Unable to compile LaTeX code" >&2
		exit 1
	fi
	$dcommand ${file/%tex/dvi} > /dev/null
}

clean()
{
	rm -f ${file/%tex/aux} ${file/%tex/dvi} ${file/%tex/log} $file
}

##----MAIN----##
chkargs $*
cat > $file <<- EOF
	\documentclass{article}
	\usepackage[american]{babel}
	\usepackage{amsmath}
	\usepackage{amssymb}
	\usepackage{amsfonts}
	\pagestyle{empty}
	\newcommand{\abs}[1]{\lvert#1\rvert}
	\newcommand{\s}{\Rightarrow}
	\begin{document}
	$size
	\$\$${text}\$\$
	\end{document}
	EOF
convert
clean

echo "${file/%tex/png}"

exit 0
