#!/bin/bash

##
# turl    -- shorten a url using tinyurl.com
#
# usage   -- turl URL
#         -- Alternatively, accepts stdin
#
# notes   -- watch out for ampersands
#            and other special characters
#
# written -- 4 July, 2010 by Egan McComb
#
# revised -- 20 June, 2011 by author
##

service="http://tinyurl.com/create.php"

usage()
{
	echo "Usage: $(basename $0) URL" >&2
	echo -e "\t-Alternatively, accepts stdin" >&2
	echo -e "\t-Watch out for ampersands" >&2
	echo -e "\t and other special characters" >&2
}

posturl()
{
	curl -s -d url="$url" "$service" 2> /dev/null || { echo "Error: Transmission failed" >&2; exit 1; }
}

chkargs()
{
	if (( ! $# )) && [[ -t 0 ]] 
	then
		echo "Error: No input given" >&2
		usage
		exit $ERR_NARGS
	elif (( $# > 1 )) || { (( $# )) && [[ ! -t 0 ]]; }
	then
		echo "Error: Excess input" >&2
		usage
		exit $ERR_NARGS
	elif (( $# ))
	then
		url="$1"
	else
		read -r url
	fi
}

##----MAIN----##
if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

chkargs "$@"

posturl | sed -n 's/.*\(http:\/\/tinyurl.com\/[a-z0-9][a-z0-9]*\).*/\1/p' | uniq | tclip

exit 0
