#!/bin/bash

##
# turl -- shorten a url using tinyurl.com
#
# usage -- turl URL, accepts stdin
#
# notes -- watch out for problematic characters
#
# written -- 4 July, 2010 by Egan McComb
#
# revised -- 20 June, 2011 by author
##

err_nargs=3

command="curl"
coption=" -s -d"
pstdata='url="$URL"'
service="http://tinyurl.com/create.php"

usage()
{
	echo "Usage: $(basename $0) URL" >&2
	echo -e "\t-Alternatively, accepts stdin" >&2
	echo -e "\t-Watch out for ampersands" >&2
	echo -e "\t and other special characters" >&2
}

chkargs()
{
	if [ -z "$1" ] && [ -t 0 ] 
	then
		echo "Error: No input given" >&2
		usage
		exit $err_nargs
	elif [ $# -gt 1 ] || [ ! -z "$1" ] && [ ! -t 0 ]
	then
		echo "Error: Excess input" >&2
		usage
		exit $err_nargs
	elif [ ! -z "$1" ]
	then
		url="$1"
	else
		read -r url
	fi
}

##----MAIN----##
chkargs "$@"

out=$(eval $command $coption $pstdata $service | sed -n 's/.*\(http:\/\/tinyurl.com\/[a-z0-9][a-z0-9]*\).*/\1/p' | uniq)
echo -n $out | xclip
echo $out

exit 0
