#!/bin/bash

##
# upaur		-- check arch user repository for updates to foreign packages
#
# usage		-- upaur
#
# notes		-- requires jshon, netbool.sh, and userbool.sh
#
# written	-- 2 October, 2010 by Egan McComb
#
# revised	-- 7 November, 2010 by author
#		-- 6 June, 2011 by author
##

aurl="https://aur.archlinux.org/packages"
qurl="https://aur.archlinux.org/rpc.php?type=info&arg="
pkglist=$(pacman -Qm | tr " " ";")
destdir="$HOME/src/aur"

curl()
{
	command curl -s "$@"
}

wget()
{
	command wget -qP "$@"
}

getversion()
{
	curl -s "${qurl}$pkgname" | jshon -e results -e Version -u 2> /dev/null #|| echo "UNKNOWN"
}

output()
{
	printf "%-30s -- %s\n" $pkgname "$status"
	if [[ $status = OUTDATED ]]
	then
		echo -ne "\E[01;34m::\033[0m Retrieve tarball? [Y/n] "
		read response
		if userbool.sh $response
		then
			wget $destdir $aurl/${pkgname:0:2}/$pkgname/$pkgname.tar.gz
		fi
	fi
}

##----MAIN----##
if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 1
fi

for pkg in $pkglist
do
	status="ERROR"
	pkgname=$(cut -d ";" -f 1 <<< $pkg)
	if grep -q git <<< $pkgname
	then
		status="UNKNOWN"
	else
		localversion=$(cut -d ";" -f 2 <<< $pkg)
		extrnversion=$(getversion)
		if [[ $localversion == $extrnversion ]]
		then
			status="CURRENT"
		elif [[ $localversion < $extrnversion ]]
		then
			status="OUTDATED"
		fi
	fi
	output
done

exit 0
