#!/bin/bash

##
# upaur -- check arch user repository for updates to foreign packages
#
# usage -- upaur
#
# written -- 2 October, 2010 by Egan McComb
#
# revised -- 7 November, 2010 by author
#            6 June, 2011 by author
##

aurl="http://aur.archlinux.org/packages"
aurq="http://aur.archlinux.org/rpc.php?type=info&arg="
pacq=$(pacman -Qm | tr " " ";")
dest="$HOME/src/aur"
curl="curl -s"
wget="wget -qP $DEST"

extern()
{
	extrn=$($curl ${aurq}$pkgnm | jshon -e results -e Version -u)
}

output()
{
	printf "%-30s -- %s\n" $pkgnm $status
	if [ $status = "OUTDATED" ]
	then
		echo -ne "\E[01;34m::\033[0m Retrieve tarball? [Y/n] "
		read reply
		if [ $reply = "Y" ] || [ $reply = "y" ]
		then
			$wget $aurl/$pkgnm/$pkgnm.tar.gz
		fi
	fi
}

##----MAIN----##
for pkg in $pacq
do
	pkgnm=$(cut -d ";" -f 1 <<< $pkg)
	local=$(cut -d ";" -f 2 <<< $pkg)
	extern

	if $(grep -q "git" <<< "$pkgnm")
	then
		status="UNKNOWN"
	else
		if [ $local = "$EXTRN" ]
		then
			status="CURRENT"
		else
			status="OUTDATED"
		fi
	fi
	output
done

exit 0
