#!/bin/bash

##
# upmirrors -- updates and ranks new pacman mirror list
#
# usage     -- upmirrors
#
# notes     -- requires netbool.sh and rankmirrors
#
# written   -- 18 February 2012 by Egan McComb
#
# revised   --
##

listpacnew="/etc/pacman.d/mirrorlist.pacnew"
listorig="/etc/pacman.d/mirrorlist.orig"
list="/etc/pacman.d/mirrorlist"


##----MAIN----##
if [[ $EUID != "0" ]]
then
	echo "Error: Must be root"
	exit 1
fi

if ! netbool.sh
then
	echo "Error: Internet connectivity poor" >&2
	exit 2
fi

if [[ -e "$listpacnew" ]]
then
	echo "Installing pacnew file..."
	mv "$listpacnew" "$listorig" &> /dev/null || { echo "Error: Could not install pacnew file" >&2; exit $ERR_VARGS; }
	echo "Enabling 'Any' and 'United States' mirrors..."
	sed -i '/## \(United States\|Any\)/,/^$/s/#Server/Server/g' "$listorig"
fi

if [[ ! -e "$listorig" ]]
then
	echo "Original mirrorlist missing" >&2
	echo "Backing up current mirrorlist..."
	cp "$list" "$listorig" &> /dev/null || { echo "Error: Could not back up mirrorlist" >&2; exit $ERR_VARGS; }
	echo "Please check that $listorig is complete" >&2
fi

echo "Ranking mirrors..."
rankmirrors "$listorig" > "$list"
echo "Cleaning up output file..."
sed -i '/^#[^ ]/d' "$list"

exit 0
