#!/bin/bash

##
# wcshot	-- take live webcam shots via mplayer
#
# usage		-- wcshot [WxH]
#			-Press s to take a shot
#			-Press S to start/stop taking
#			 continuous shots
#			-Press q to quit
#
# notes		-- expects webcam at /dev/video0
#		-- default aspect ratio is 640x480
#
# written	-- 20 June, 2011 by Egan McComb
#
# revised	--
##

coption="-msglevel all=-1:cplayer=-1:statusline=-1 -vf screenshot"
vdevice="tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0"

usage()
{
	echo "Usage: $(basename $0) [WxH]" >&2
	echo -e "\t-Press s to take a shot" >&2
	echo -e "\t-Press S to start/stop taking" >&2
	echo -e "\t continuous shots" >&2
	echo -e "\t-Press q to quit" >&2
	echo "Note: Expects webcam at /dev/video0" >&2
	echo -e "\t-Default resolution is 640x480" >&2
}

opendevice()
{
	mplayer $coption $vdevice
}

chkargs()
{
	if (( $# > 1 ))
	then
		echo "Error: Too many arguments" >&2
		usage
		exit $ERR_NARGS
	elif (( $# )) && [[ $1 = -h ]]
	then
		usage
		exit 0
	elif (( $# )) && ! grep -q [[:digit:]]x[[:digit:]] <<< "$1"
	then
		echo "Error: Invalid resolution '$1'" >&2
		usage
		exit $ERR_VARGS
	elif (( $# ))
	then
		vdevice=${vdevice/640/$(cut -d x -f 1 <<< $1)}
		vdevice=${vdevice/480/$(cut -d x -f 2 <<< $1)}
	fi
}

##----MAIN----##
chkargs "$@"

echo "Wait a few seconds for the device to be opened" >&2
echo "==============================================" >&2
echo "Press s to take a shot, or S to start/stop taking continuous shots" >&2
echo "Shots will be saved in current directory as shotNNNN.png" >&2
echo
echo "Press q to quit" >&2
opendevice &> /dev/null || { echo "Error: MPlayer crashed" >&2; exit 1; }

exit 0
