#!/bin/bash

##
# wcshot -- take live webcam shots via mplayer
#
# usage -- wcshot
#		-Press s to take a shot
#		-Press S to start/stop taking
#		 continuous shots
#		-Press q to quit.
#
# notes -- assumes webcam is at /dev/video0
#	   and has 640x480 resolution
#
# written -- 20 June, 2011 by Egan McComb
#
# revised --
##

COMMAND="mplayer"
COPTION="-msglevel all=-1:cplayer=-1:statusline=-1 -vf screenshot"
VDEVICE="tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0"

echo "Wait a few seconds for the device to be opened" >&2
echo "==============================================" >&2
echo "Press s to take a shot, or S to start/stop taking continuous shots" >&2
echo "Shots will be saved in current directory as shotNNNN.png" >&2
echo
echo "Press q to quit" >&2
$COMMAND $COPTION $VDEVICE &> /dev/null || echo "Error: Mplayer crashed" >&2 && exit 1
exit 0
