#!/bin/bash

##
# xdostart -- rudimentary startup routine implemented with xdotool
#
# usage    -- xdostart
#
# notes    -- designed for use from run dialog
#          -- very specialized for personal use
#
# written  -- 3 December, 2010 by Egan McComb
#
# revised  -- 7 April, 2013 by Egan McComb
##

delay=100

[[ $(wpa_cli -i wlan0 status | sed -n 's/^id_str=//p') = "Crazy_Eights-wireless" ]] && sshc='exec mosh paijanne
' || sshc='exec ssh -p 2222 u8
'

xdotool key --delay $delay super+1 super+x super+x super+x
xdotool key --delay $delay super+2 super+x super+x super+v super+x
xdotool key --delay $delay super+3 super+x super+x super+x
xdotool key --delay $delay super+5 super+v super+x super+x
:
xdotool key --delay $delay super+1 super+j type 'nettest
'
xdotool key --delay $delay super+k super+2 type 'ls
'
xdotool key --delay $delay super+j type ':cd notes/
'
xdotool key --delay $delay super+k type 'la
'
xdotool key --delay $delay super+j type ':e todo.txt
'
xdotool key --delay $delay super+k super+3 type "$sshc"
xdotool key --delay $delay super+j type 'exec mail
'
xdotool key --delay $delay super+k super+5 type 'cd music/rec/
'
xdotool key --delay $delay super+j type 'cd music/rec/
'
xdotool key --delay $delay super+j type ':cd notes/
'
xdotool key --delay $delay super+k type 'ls
'
xdotool key --delay $delay super+j type ':e music.txt
'
xdotool key --delay $delay super+j super+1

exit 0
