#!/bin/bash

##
# xdostart -- rudimentary startup routine implemented with xdotool
#
# usage -- typically run by ~/.xinitrc or through a run dialog
# 
# notes -- very specialized for personal use
#
# written -- 3 December, 2010 by Egan McComb
#
# revised --
##

DELAY=40

xdotool key --delay $DELAY super+1 super+x super+x super+x
xdotool key --delay $DELAY super+2 super+x super+x super+v super+x
xdotool key --delay $DELAY super+3 super+x super+x super+x
xdotool key --delay $DELAY super+5 super+x super+x super+x
xdotool key --delay $DELAY super+1 super+j type 'nettest
'
xdotool key --delay $DELAY super+k super+2 type 'ls
'
xdotool key --delay $DELAY super+j type ':cd notes/
'
xdotool key --delay $DELAY super+k type 'la
'
xdotool key --delay $DELAY super+j type ':e todo.txt
'
xdotool key --delay $DELAY super+k super+3 type 'exec ssh paijanne
'
xdotool key --delay $DELAY super+j type 'exec mutt
'
xdotool key --delay $DELAY super+k super+5 type 'cd music/rec/
'
xdotool key --delay $DELAY super+j type 'cd music/rec/
'
xdotool key --delay $DELAY super+j type 'cd var/
'
xdotool key --delay $DELAY super+k type 'ls
'
xdotool key --delay $DELAY super+k super+1

exit 0
